julia: move to 1.2.0 + trunk, use external LLVM
Build with the proper LLVM version, use not rc1 but newer revision to
have working build system customizations (without patching build system
files).

Error message «du jour»:

    ┌ Warning: No working GUI backend found for matplotlib
    └ @ PyPlot ~/.cache/spack/linux-rhel7-x86_64/gcc-6.4.0/julia-1.2.0-rc1-snapshot0-d2gfb5/var/julia/pkg/packages/PyPlot/cdCMF/
    src/init.jl:155
    ERROR: InitError: PyError (PyImport_ImportModule

    The Python package matplotlib.pyplot could not be found by pyimport. Usually this means
    that you did not install matplotlib.pyplot in the Python version being used by PyCall.